using Loyc.MiniTest;
using Loyc.SyncLib;
using System;
using System.Collections.Generic;
using System.Numerics;

namespace Loyc.SyncLib.Tests
{
	/// <summary>Tests for <see cref="SyncProtobuf.Schema"/>, which generates proto3
	/// <c>.proto</c> definitions describing the output of <see cref="SyncProtobuf.Writer"/>.</summary>
	[TestFixture]
	public class SyncProtobufSchemaTests : Assert
	{
		#region Test models and synchronizers

		class PrimModel
		{
			public int Int; public uint UInt; public long Lng; public ulong ULng;
			public short Sh; public ushort USh; public sbyte Sb; public byte By;
			public bool Flag; public float F; public double D; public decimal Dec;
			public BigInteger Big; public char Ch; public string? Name;
			public int? MaybeInt; public byte[]? Blob; public int[]? Ints; public bool[]? Bools;
			public char[]? Chars; public string[]? Strings;
		}

		static PrimModel SyncPrim(ISyncManager sm, PrimModel? m)
		{
			m ??= new PrimModel();
			m.Int = sm.Sync("Int", m.Int);
			m.UInt = sm.Sync("UInt", m.UInt);
			m.Lng = sm.Sync("Lng", m.Lng);
			m.ULng = sm.Sync("ULng", m.ULng);
			m.Sh = sm.Sync("Sh", m.Sh);
			m.USh = sm.Sync("USh", m.USh);
			m.Sb = sm.Sync("Sb", m.Sb);
			m.By = sm.Sync("By", m.By);
			m.Flag = sm.Sync("Flag", m.Flag);
			m.F = sm.Sync("F", m.F);
			m.D = sm.Sync("D", m.D);
			m.Dec = sm.Sync("Dec", m.Dec);
			m.Big = sm.Sync("Big", m.Big);
			m.Ch = sm.Sync("Ch", m.Ch);
			m.Name = sm.Sync("Name", m.Name);
			m.MaybeInt = sm.Sync("MaybeInt", m.MaybeInt);
			m.Blob = sm.SyncList("Blob", m.Blob);
			m.Ints = sm.SyncList("Ints", m.Ints);
			m.Bools = sm.SyncList("Bools", m.Bools);
			m.Chars = sm.SyncList("Chars", m.Chars);
			m.Strings = sm.SyncList("Strings", m.Strings);
			return m;
		}

		class Person { public string? Name; public int Age; public Person[]? Siblings; }
		static Person SyncPerson(ISyncManager sm, Person? p)
		{
			p ??= new Person();
			p.Name = sm.Sync(("Name", 1), p.Name);
			p.Age = sm.Sync(("Age", 2), p.Age);
			p.Siblings = sm.SyncList(("Siblings", 3), p.Siblings, SyncPerson);
			return p;
		}

		class Parent { public string? Name; public List<Child>? Children; }
		class Child { public string? Name; public Parent? Father; public Parent? Mother; }
		static Parent SyncParent(ISyncManager sm, Parent? o)
		{
			o ??= new Parent();
			o.Name = sm.Sync("Name", o.Name);
			o.Children = sm.SyncList("Children", o.Children, SyncChild, ObjectMode.Deduplicate);
			return o;
		}
		static Child SyncChild(ISyncManager sm, Child? c)
		{
			sm.CurrentObject = c ??= new Child();
			c.Name = sm.Sync("Name", c.Name);
			c.Father = sm.Sync("Father", c.Father, SyncParent, ObjectMode.Deduplicate);
			c.Mother = sm.Sync("Mother", c.Mother, SyncParent, ObjectMode.Deduplicate);
			return c;
		}

		class Shape { public double Size; }
		static Shape SyncShape(ISyncManager sm, Shape? s)
		{
			sm.SyncTypeTag("Ellipse");
			s ??= new Shape();
			s.Size = sm.Sync("Size", s.Size);
			return s;
		}

		// Same type synchronized two conflicting ways -> EndSubObject must throw.
		class Widget { public int A; public string? B; }
		class WidgetHolder { public Widget? W1, W2; }
		static Widget SyncWidgetA(ISyncManager sm, Widget? w) { w ??= new Widget(); w.A = sm.Sync("A", w.A); return w; }
		static Widget SyncWidgetB(ISyncManager sm, Widget? w) { w ??= new Widget(); w.B = sm.Sync("B", w.B); return w; }
		static WidgetHolder SyncHolderConflict(ISyncManager sm, WidgetHolder? h)
		{
			h ??= new WidgetHolder();
			h.W1 = sm.Sync("W1", h.W1, SyncWidgetA, ObjectMode.NotNull);
			h.W2 = sm.Sync("W2", h.W2, SyncWidgetB, ObjectMode.NotNull);
			return h;
		}

		#endregion

		// Compares .proto documents, tolerant of CRLF vs LF.
		static void CheckProto(string expected, string actual)
			=> AreEqual(expected.Replace("\r\n", "\n"), actual.Replace("\r\n", "\n"));

		const string Header =
			"// Generated by Loyc.SyncLib SyncProtobuf.Schema.\n" +
			"// A proto3 schema describing the messages that SyncProtobuf.Writer produces.\n" +
			"syntax = \"proto3\";\n";

		[Test]
		public void PrimitiveFieldsSchema()
		{
			CheckProto(Header + @"
message PrimModel {
  int32 Int = 1;
  uint32 UInt = 2;
  int64 Lng = 3;
  uint64 ULng = 4;
  int32 Sh = 5;
  uint32 USh = 6;
  int32 Sb = 7;
  uint32 By = 8;
  bool Flag = 9;
  float F = 10;
  double D = 11;
  bytes Dec = 12;
  bytes Big = 13;
  uint32 Ch = 14;
  optional string Name = 15;
  optional int32 MaybeInt = 16;
  repeated uint32 Blob = 17;
  repeated int32 Ints = 18;
  repeated bool Bools = 19;
  repeated uint32 Chars = 20;
  repeated string Strings = 21;
}
".Replace("\r\n", "\n"),
				SyncProtobuf.WriteSchemaStringI<PrimModel>(SyncPrim));
		}

		[Test]
		public void RecursiveTypeSchema()
		{
			// Explicit field numbers (1,2,3) and a recursive "repeated Person" field.
			CheckProto(Header + @"
message Person {
  optional string Name = 1;
  int32 Age = 2;
  repeated Person Siblings = 3;
}
".Replace("\r\n", "\n"),
				SyncProtobuf.WriteSchemaStringI<Person>(SyncPerson));
		}

		[Test]
		public void CyclicTypesSchema()
		{
			// Parent <-> Child cycle with deduplication (dedup is a wire concern and does
			// not appear in the logical .proto schema).
			CheckProto(Header + @"
message Parent {
  optional string Name = 1;
  repeated Child Children = 2;
}

message Child {
  optional string Name = 1;
  Parent Father = 2;
  Parent Mother = 3;
}
".Replace("\r\n", "\n"),
				SyncProtobuf.WriteSchemaStringI<Parent>(SyncParent));
		}

		[Test]
		public void TypeTagNamesTheMessage()
		{
			CheckProto(Header + @"
message Ellipse {
  double Size = 1;
}
".Replace("\r\n", "\n"),
				SyncProtobuf.WriteSchemaStringI<Shape>(SyncShape));
		}

		[Test]
		public void ExplicitFieldNumbersWithGaps()
		{
			string proto = SyncProtobuf.WriteSchemaStringI<int>((sm, _) => {
				sm.Sync(("a", 5), 0);
				sm.Sync(("b", 900), 0L);
				return 0;
			});
			IsTrue(proto.Contains("int32 a = 5;"), "missing 'int32 a = 5;' in:\n" + proto);
			IsTrue(proto.Contains("int64 b = 900;"), "missing 'int64 b = 900;' in:\n" + proto);
		}

		[Test]
		public void ConflictingSchemasThrow()
		{
			bool threw = false;
			try {
				SyncProtobuf.WriteSchemaStringI<WidgetHolder>(SyncHolderConflict);
			} catch (InvalidOperationException) {
				threw = true;
			}
			IsTrue(threw, "Expected an InvalidOperationException for conflicting schemas of one type");
		}
	}
}
