Enhanced C#: Loyc.Syntax.ParsingMode Class Reference
Loyc.Syntax.ParsingMode Class Reference
Standard parsing modes used with IParsingService and ILNodePrinterOptions.
Source file:
/Core/Loyc.Syntax/LNodes/ParsingMode.cs
Remarks
Standard parsing modes used with IParsingService and ILNodePrinterOptions.
Public static fields
static new readonly SymbolPool< ParsingMode > Pool = new SymbolPool<ParsingMode>(p => new ParsingMode(p))
static readonly ParsingMode Expressions = Pool.Get("Exprs")
Tells IParsingService.Parse to treat the input as a single expression or expression list (which, in most languages, is comma-separated).
static readonly ParsingMode Statements = Pool.Get("Stmts")
Tells IParsingService.Parse to treat the input as a list of statements. If the language makes a distinction between executable and declaration contexts, this refers to the executable context.
static readonly ParsingMode Declarations = Pool.Get("Decls")
Tells IParsingService.Parse to treat the input as a list of statements. If the language makes a distinction between executable and declaration contexts, this refers to the declaration context, in which types, methods, and properties are recognized.
static readonly ParsingMode Types = Pool.Get("Types")
Tells IParsingService.Parse to treat the input as a list of types (or a single type, if a list is not supported).
static readonly ParsingMode FormalArguments = Pool.Get("FormalArguments")
Tells IParsingService.Parse to treat the input as a formal argument list (parameter names with types).
static readonly ParsingMode File = Pool.Get("File")
Tells IParsingService.Parse to treat the input as a complete source file (this should be the default, i.e. null will do the same thing).
Additional Inherited Members
Properties inherited from Loyc.Symbol
string Name [get]
Gets the name of the Symbol.
SymbolPool Pool [get]
Gets the SymbolPool in which this Symbol was created.
bool IsGlobal [get]
Returns true if this symbol is in the global pool (GSymbol.Pool).
int Id [get]
Returns a numeric ID for the Symbol.
Public Member Functions inherited from Loyc.Symbol
override string ToString ()
override int GetHashCode ()
override bool Equals (object b)
bool Equals (Symbol b)
int CompareTo (Symbol other)
Static Public Member Functions inherited from Loyc.Symbol
static operator Symbol (string s)
static operator string (Symbol s)
static operator Symbol (UString s)
static operator UString (Symbol s)
static Symbol For (string s)
Alias for GSymbol.Get(string). This function was introduced to match the equivalent ES6 API Symbol.for("string")
Protected Member Functions inherited from Loyc.Symbol
Symbol (Symbol prototype)
For use by a derived class to produce a statically-typed enumeration in a private pool. See the example under SymbolPool (of SymbolEnum)
Member Data Documentation
readonly ParsingMode Loyc.Syntax.ParsingMode.Declarations = Pool.Get("Decls") static
Tells IParsingService.Parse to treat the input as a list of statements. If the language makes a distinction between executable and declaration contexts, this refers to the declaration context, in which types, methods, and properties are recognized.
readonly ParsingMode Loyc.Syntax.ParsingMode.Expressions = Pool.Get("Exprs") static
Tells IParsingService.Parse to treat the input as a single expression or expression list (which, in most languages, is comma-separated).
Referenced by LeMP.Compiler.AddStdMacros(), Loyc.LLParserGenerator.AndPred.Clone(), Loyc.LLParserGenerator.GeneralCodeGenHelper.Example(), Loyc.LLParserGenerator.CodeGenHelperBase.GenerateAndPredCheck(), Loyc.Syntax.Les.Les2LanguageService.Parse(), Loyc.Syntax.Les.Les3LanguageService.Parse(), Loyc.Ecs.EcsLanguageService.Parse(), Loyc.Ecs.EcsNodePrinter.PrintECSharp(), and Loyc.LLParserGenerator.PGNodeSet.WithEOF().
readonly ParsingMode Loyc.Syntax.ParsingMode.File = Pool.Get("File") static
Tells IParsingService.Parse to treat the input as a complete source file (this should be the default, i.e. null will do the same thing).
Referenced by LeMP.Compiler.AddStdMacros(), and Loyc.Syntax.ParsingService.ParseFile().
readonly ParsingMode Loyc.Syntax.ParsingMode.FormalArguments = Pool.Get("FormalArguments") static
Tells IParsingService.Parse to treat the input as a formal argument list (parameter names with types).
Referenced by Loyc.Ecs.EcsLanguageService.Parse().
readonly ParsingMode Loyc.Syntax.ParsingMode.Statements = Pool.Get("Stmts") static
Tells IParsingService.Parse to treat the input as a list of statements. If the language makes a distinction between executable and declaration contexts, this refers to the executable context.
readonly ParsingMode Loyc.Syntax.ParsingMode.Types = Pool.Get("Types") static
Tells IParsingService.Parse to treat the input as a list of types (or a single type, if a list is not supported).
Referenced by Loyc.Ecs.EcsLanguageService.Parse().