Enhanced C#: Loyc.Ecs.Parser.EcsTriviaInjector Class Reference
Loyc.Ecs.Parser.EcsTriviaInjector Class Reference
Trivia injector customized for Enhanced C#.
Source file:
/Main/Ecs/Parser/EcsTriviaInjector.cs
Remarks
Trivia injector customized for Enhanced C#.
How newline trivia works in EC# (mostly this is the same as StandardTriviaInjector):
Implicitly, there is a newline before every node within a braced block, and CodeSymbols.TriviaAppendStatement is required to suppress it. The Loyc tree does not specify whether or not there is a newline before the closing brace; it is assumed that there should be a newline unless ALL children of the braced block use appendStatement.
Implicitly, there is a newline before every top-level statement except the first, and appendStatement can be used to suppress it.
By default, the printer doesn't print a newline before an opening brace. newline can be added (as an attribute) to the braced block node to represent one.
This injector explicitly encodes newlines in all other locations. However, the EC# printer is designed to print all syntax trees reasonably whether they have passed through the trivia injector or not. Therefore, on non-braced-block child statements of certain nodes (if statements, while loops, for loops, and other statements used without braces), the printer will print a newline before a child statement if it does not have newline or appendStatement attributes.
In an if-else statement, else has no representation in the syntax tree and may appear to the injector the same as a blank line. In this situation two newlines are attached to the child of #if at index 2, and one is deleted by this class so that there is only one newline before the second child.
Constructors that call another constructor (: base(...)) get a newline before the colon by default, which can be suppressed with appendStatement. Note: These constructors have an unusual syntax tree which the standard trivia injector can't handle properly; see comment in DoneAttaching() for details.
Public Member Functions
EcsTriviaInjector (IListSource< Token > sortedTrivia, ISourceFile sourceFile, int newlineTypeInt, string mlCommentPrefix, string mlCommentSuffix, string slCommentPrefix, bool topLevelIsBlock)
Public Member Functions inherited from Loyc.Syntax.StandardTriviaInjector
StandardTriviaInjector (IListSource< Token > sortedTrivia, ISourceFile sourceFile, int newlineTypeInt, string mlCommentPrefix, string mlCommentSuffix, string slCommentPrefix, bool topLevelIsBlock=true)
Initializes StandardTriviaInjector.
Public Member Functions inherited from Loyc.Syntax.AbstractTriviaInjector< Token >
AbstractTriviaInjector (IListSource< Trivia > sortedTrivia)
Initializes the SortedTrivia property.
IEnumerator< LNode > Run (IEnumerator< LNode > nodes)
Attaches trivia to the input nodes provided.
Protected Member Functions
override LNodeList GetTriviaToAttach (LNode node, IListSource< Token > trivia, TriviaLocation loc, LNode parent, int indexInParent)
override LNode MakeTriviaAttribute (Token t)
Called to transform a trivia token into a trivia attribute.
override LNode DoneAttaching (LNode node, LNode parent, int indexInParent)
This method is called after a node has been processed and any applicable trivia was attached.
Protected Member Functions inherited from Loyc.Syntax.StandardTriviaInjector
override LNodeList GetTriviaToAttach (LNode node, IListSource< Token > trivia, TriviaLocation loc, LNode parent, int indexInParent)
virtual bool HasImplicitLeadingNewline (LNode child, LNode parent, int indexInParent)
Called to find out if a newline is to be added implicitly before the current child of the specified node.
override bool IsNewline (Token trivia)
override SourceRange GetRange (Token trivia)
Protected Member Functions inherited from Loyc.Syntax.AbstractTriviaInjector< Token >
abstract LNodeList GetTriviaToAttach (LNode node, IListSource< Trivia > trivia, TriviaLocation loc, LNode parent, int indexInParent)
Derived class translates a list of trivia (tokens) into appropriate trivia attributes. This will be called for leading trivia before trailing trivia.
virtual void ProcessChildrenOfOneLiner (ref LNode node)
This method is called when a node has no newlines or comments within it (although the node may still have a leading or trailing comment). The method should add appendStatement trivia inside blocks in the node, if necessary.
abstract SourceRange GetRange (Trivia trivia)
Gets the SourceRange for an element of trivia.
abstract bool IsNewline (Trivia trivia)
Returns true if the trivia represents a newline, false otherwise.
virtual LNode GetEmptyResultSet ()
A method called to create a virtual node, in order to apply trivia to a source file that is completely empty except for trivia.
IEnumerator< Pair< LNode, int > > RunCore (IEnumerator< Pair< LNode, int >> nodes, LNode parent)
Core trivia associaton algorithm.
Additional Inherited Members
Properties inherited from Loyc.Syntax.StandardTriviaInjector
ISourceFile SourceFile [get, set]
int NewlineTypeInt [get, set]
string SLCommentPrefix [get, set]
string SLCommentSuffix [get, set]
string MLCommentPrefix [get, set]
string MLCommentSuffix [get, set]
bool TopLevelIsBlock [get, set]
Properties inherited from Loyc.Syntax.AbstractTriviaInjector< Token >
IListSource< Trivia > SortedTrivia [get, set]
List of trivia to be injected by Run. Must be sorted.
int NextIndex [get, set]
Index of next trivia to be injected.
Static Protected Member Functions inherited from Loyc.Syntax.AbstractTriviaInjector< Token >
static IEnumerator< Pair< T, int > > WithIndexes< T > (IEnumerator< T > e)
Member Function Documentation
DoneAttaching()
override LNode Loyc.Ecs.Parser.EcsTriviaInjector.DoneAttaching (LNode node, LNode parent, int indexInParent) inline protected virtual
This method is called after a node has been processed and any applicable trivia was attached.
Parameters
node Node (after trivia attached)
parent Parent of node (old version, before changes to children are applied)
indexInParent Index of node within parent.
Returns
Should return node or an altered version of node.
This method gives the derived class one final chance to rearrange or alter the interpretation of the attached trivia. Note that this method may be called on some nodes to which trivia was not attached, when siblings of the same parent had trivia attached.
Reimplemented from Loyc.Syntax.AbstractTriviaInjector< Token >.
References Loyc.Syntax.LNode.Args, Loyc.Syntax.CodeSymbols.Braces, Loyc.Syntax.LNode.Calls(), Loyc.Syntax.LNode.CallsMin(), Loyc.Syntax.LNode.Range, and Loyc.Syntax.LNode.Target.
MakeTriviaAttribute()
override LNode Loyc.Ecs.Parser.EcsTriviaInjector.MakeTriviaAttribute (Token t) inline protected virtual
Called to transform a trivia token into a trivia attribute.
If a trivia token is not recognized, null is returned to ignore the trivia.
Reimplemented from Loyc.Syntax.StandardTriviaInjector.
References Loyc.Syntax.Lexing.Token.Range(), and Loyc.Syntax.Lexing.Token.Value.