Enhanced C#: Loyc.LLPG.Macros Class Reference
Loyc.LLPG.Macros Class Reference
Macros for using LLLPG in LeMP.
Source file:
/Main/LLLPG/ParsersAndMacros/Macros.cs
Remarks
Macros for using LLLPG in LeMP.
Example:
class Foo {
  [DefaultK(2)] LLLPG lexer
  {
    private rule Int '0'..'9'+ };
    private rule Id 'a'..'z'|'A'..'Z' ('a'..'z'|'A'..'Z'|'0'..'9'|'_')* };
    token Token Int | Id };
  };
};
Up to three macros are used to invoke LLLPG.
there is a macro to recognize the pattern LLLPG(lexer, {...}) and translate "lexer" to an unprintable literal of type IntStreamCodeGenHelper, and another macro for LLLPG(parser(Symbol, false), {...})"</c> that creates a <see cref="GeneralCodeGenHelper"/> (this is the default helper).</li> <li>The stage-one rule() macro uses <see cref="StageOneParser"/> to translate token trees into expressions, e.g. <c>@[ ("Foo" | bar)* ~';' ]</c> is currently translated to <c>#tuple(@`suf*`("Foo" | bar), ~';').
The stage-two macro is named run_LLLPG(). It accepts the code-gen helper created by the LLLPG(lexer) or LLLPG(parser) macro, and it has the ProcessChildrenBefore flag so that the stage-1 rule() macros run first. run_LLLPG calls StageTwoParser to translate expressions into Pred objects, and then invokes LLParserGenerator to analyze the grammar and generate code.
Public static fields
static readonly Symbol MacroNamespace = GSymbol.Get("Loyc.LLPG")
Static Public Member Functions
static LNode LLLPG_lexer (LNode node, IMacroContext context)
Helper macro that translates lexer in LLLPG(lexer, {...}) into a IntStreamCodeGenHelper object.
static LNode LLLPG_parser (LNode node, IMacroContext context)
Helper macro that translates parser in LLLPG(parser, {...}) into a GeneralCodeGenHelper object.
static LNode LllpgMacro (LNode node, IMacroContext context, Symbol expectedCodeGenMode, Func< LNode, IPGCodeGenHelper > makeCodeGenHelper, bool isDefault=false)
This method helps do the stage-one transform from LLLPG (config) {...} to run_LLLPG (helper literal) {...} and also invokes the ANTLR-style parser if the second argument is a token literal. If node[0] calls expectedConfigNode then the delegate is called to construct a code generation helper object; otherwise, this method has no effect and returns null.
static LNode rule (LNode node, IMacroContext context)
static LNode ECSharpRule (LNode node, IMacroContext context)
static LNode run_LLLPG (LNode node, IMacroContext context)
Member Function Documentation
static LNode Loyc.LLPG.Macros.LLLPG_lexer (LNode node, IMacroContext context) inline static
Helper macro that translates lexer in LLLPG(lexer, {...}) into a IntStreamCodeGenHelper object.
References LeMP.MacroContext.GetOptions(), LeMP.LexicalMacro(), Loyc.Syntax.LNode.Value, and Loyc.IMessageSink.Write().
static LNode Loyc.LLPG.Macros.LLLPG_parser (LNode node, IMacroContext context) inline static
Helper macro that translates parser in LLLPG(parser, {...}) into a GeneralCodeGenHelper object.
References LeMP.MacroContext.GetOptions(), Loyc.Syntax.LNode.Value, and Loyc.IMessageSink.Write().
static LNode Loyc.LLPG.Macros.LllpgMacro (LNode node, IMacroContext context, Symbol expectedCodeGenMode, Func< LNode, IPGCodeGenHelper > makeCodeGenHelper, bool isDefault = false) inline static
This method helps do the stage-one transform from LLLPG (config) {...} to run_LLLPG (helper literal) {...} and also invokes the ANTLR-style parser if the second argument is a token literal. If node[0] calls expectedConfigNode then the delegate is called to construct a code generation helper object; otherwise, this method has no effect and returns null.
References Loyc.LLParserGenerator.LLParserGenerator.AddComments, Loyc.LLParserGenerator.LLParserGenerator.AddCsLineDirectives, Loyc.Syntax.LNode.Args, Loyc.Syntax.LNode.Attrs, Loyc.LLParserGenerator.LLParserGenerator.DefaultK, Loyc.LLParserGenerator.LLParserGenerator.FullLLk, Loyc.Collections.VList< T >.Last, LeMP.LexicalMacro(), Loyc.Localize.Localized(), Loyc.Symbol.Name, Loyc.Syntax.LNode.Name, Loyc.LLParserGenerator.LLParserGenerator.NoDefaultArm, LeMP.IMacroContext.PreProcessChildren(), Loyc.Syntax.LNode.Range, LeMP.IMacroContext.Sink, Loyc.Collections.VList< T >.SmartSelect(), Loyc.Syntax.LNode.Source, Loyc.Syntax.LNode.Style, Loyc.Syntax.LNode.Target, Loyc.Syntax.LNode.Value, Loyc.LLParserGenerator.LLParserGenerator.Verbosity, Loyc.Syntax.LNode.With(), Loyc.Syntax.CallNode.WithArgs(), and Loyc.IMessageSink.Write().