Enhanced C#: Loyc.Collections.FWList< T > Class Template Reference
Loyc.Collections.FWList< T > Class Template Reference
FWList is the mutable variant of the FVList data structure.
Source file:
/Core/Loyc.Collections/VLists/FWList.cs
Remarks
FWList is the mutable variant of the FVList data structure.
An article is available online about the VList data types.
See the remarks of VListBlock<T> for more information about VLists and WLists. It is most efficient to add items to the front of a FWList (at index 0) or the back of an WList (at index Count-1).
Properties
new T this[int index] [get, set]
T this[int index, T defaultValue] [get]
Gets an item from the list at the specified index; returns defaultValue if the index is not valid.
T First [get]
Returns the front item of the list (at index 0).
bool IsEmpty [get]
Properties inherited from Loyc.Collections.WListBase< T >
T this[int index] [get, set]
new int Count [get]
bool IsReadOnly [get]
new int BlockChainLength [get]
Properties inherited from Loyc.Collections.WListProtected< T >
byte UserByte [get, set]
An additional byte that the derived class can optionally use.
int BlockChainLength [get]
Gets the number of blocks used by this list.
Public Member Functions
FWList (int initialSize)
FWList (T itemZero, T itemOne)
FWList (IList< T > list)
void AddRange (IList< T > list)
void InsertRange (int index, IList< T > list)
void RemoveRange (int index, int count)
new void Insert (int index, T item)
new void RemoveAt (int index)
new FVList< T >.Enumerator GetEnumerator ()
VList< T >.Enumerator ReverseEnumerator ()
new T TryGet (int index, out bool fail)
FWList< T > Clone ()
FWList< T > SmartWhere (Func< T, bool > keep)
Applies a filter to a list, to exclude zero or more items.
FWList< T > WhereSelect (Func< T, Maybe< T >> filter)
Filters and maps a list with a user-defined function.
FWList< T > SmartSelect (Func< T, T > map)
Maps a list to another list of the same length.
FWList< T > Transform (VListTransformer< T > x)
Transforms a list (combines filtering with selection and more).
T Pop ()
Removes the front item (at index 0) from the list and returns it.
FVList< T > WithoutFirst (int numToRemove)
WList< T > ToWList ()
Returns this list as an WList, which effectively reverses the order of the elements.
T[] ToArray ()
Returns the FWList converted to an array.
Public Member Functions inherited from Loyc.Collections.WListBase< T >
new void Add (T item)
new void Clear ()
new void Insert (int index, T item)
new void RemoveAt (int index)
new int IndexOf (T item)
new bool Contains (T item)
new void CopyTo (T[] array, int arrayIndex)
new bool Remove (T item)
IEnumerator< T > GetEnumerator ()
T TryGet (int index, out bool fail)
Slice_< T > Slice (int start, int count)
void Push (T item)
Synonym for Add(); adds an item to the front of the list.
new FVList< T > ToFVList ()
new VList< T > ToVList ()
Public Member Functions inherited from Loyc.Collections.IListSource< T >
T TryGet (int index, out bool fail)
Gets the item at the specified index, and does not throw an exception on failure.
IRange< T > Slice (int start, int count=int.MaxValue)
Returns a sub-range of this list.
Static Public Member Functions
static operator WList< T > (FWList< T > list)
Returns this list as an WList, which effectively reverses the order of the elements.
Static Public Member Functions inherited from Loyc.Collections.WListBase< T >
static operator FVList< T > (WListBase< T > list)
Returns this list as a FVList; if this is a WList, the order of the elements is reversed at the same time.
static operator VList< T > (WListBase< T > list)
Returns this list as a VList; if this is a FWList, the order of the elements is reversed at the same time.
Protected Member Functions
override int AdjustWListIndex (int index, int size)
This method implements the difference between FWList and WList: In FWList it returns index, but in WList it returns Count-size-index.
override IEnumerator< T > GetIEnumerator ()
Protected Member Functions inherited from Loyc.Collections.WListProtected< T >
WListProtected (WListProtected< T > original, bool takeOwnership)
T GetAt (int index)
Gets an item from a FWList or WList at the specified index.
void SetAt (int index, T value)
Sets an item in a FWList or WList at the specified index.
void Add (T item)
Inserts an item at the "front" of the list, which is index 0 for FWList, or Count for WList.
void Insert (int index, T item)
void RemoveAt (int index)
int IndexOf (T item)
Searches for the specified object and returns the zero-based index of the first occurrence (lowest index) within the entire FVList.
bool Contains (T item)
void CopyTo (T[] array, int arrayIndex)
bool Remove (T item)
FVList< T >.Enumerator GetVListEnumerator ()
VList< T >.Enumerator GetRVListEnumerator ()
void RemoveAtDff (int distanceFromFront)
void RemoveRangeBase (int distanceFromFront, int count)
void InsertRangeAtDff (int distanceFromFront, IList< T > items, bool isRWList)
void InsertAtDff (int distanceFromFront, T item)
T GetAtDff (int distanceFromFront)
Gets an item WITHOUT doing a range check
void SetAtDff (int distanceFromFront, T item)
Sets an item WITHOUT doing a range or mutability check
FVList< T > ToFVList ()
Returns this list as a FVList; if this is a WList, the order of the elements is reversed at the same time.
VList< T > ToVList ()
Returns this list as a VList; if this is a FWList, the order of the elements is reversed at the same time.
Member Function Documentation
override int Loyc.Collections.FWList< T >.AdjustWListIndex (int index, int size) inline protected virtual
This method implements the difference between FWList and WList: In FWList it returns index, but in WList it returns Count-size-index.
Parameters
index Index to adjust
size Number of elements being accessed or removed
Solely as an optimization, FWList and WList also have separate versions of this[], InsertAt and RemoveAt.
Reimplemented from Loyc.Collections.WListProtected< T >.
References Loyc.Collections.VListBlock< T >.EnsureMutable().
static Loyc.Collections.FWList< T >.operator WList< T > (FWList< T > list) inline explicit static
Returns this list as an WList, which effectively reverses the order of the elements.
This operation marks the items of the list as immutable. You can modify either list afterward, but some or all of the list may have to be copied.
T Loyc.Collections.FWList< T >.Pop () inline
Removes the front item (at index 0) from the list and returns it.
References Loyc.Collections.VListBlock< T >.EnsureImmutable().
Referenced by Loyc.Collections.FWList< T >.ToArray().
FWList<T> Loyc.Collections.FWList< T >.SmartSelect (Func< T, T > map) inline
Maps a list to another list of the same length.
Parameters
map A function that transforms each item in the list.
Returns
The list after the map function is applied to each item. The original VList structure is not modified.
This method is called "Smart" because of what happens if the map doesn't do anything. If the map function returns the first N items unmodified (the items at the tail of the FWList), those N items are typically not copied, but shared between the existing list and the new one.
References Loyc.Collections.FWList< T >.SmartSelect().
Referenced by Loyc.Collections.FWList< T >.SmartSelect().
FWList<T> Loyc.Collections.FWList< T >.SmartWhere (Func< T, bool > keep) inline
Applies a filter to a list, to exclude zero or more items.
Parameters
keep A function that chooses which items to include (exclude items by returning false).
Returns
The list after filtering has been applied. The original VList structure is not modified.
If the predicate keeps the first N items it is passed (which are the last or "tail" items in a FWList), those N items are typically not copied, but shared between the existing list and the new one.
T [] Loyc.Collections.FWList< T >.ToArray () inline
Returns the FWList converted to an array.
References Loyc.Collections.FVList< T >.Add(), Loyc.Collections.FVList< T >.BlockChainLength, Loyc.MiniTest.Assert.Fail(), Loyc.Collections.FWList< T >.First, Loyc.Collections.FWList< T >.Pop(), Loyc.Collections.FVList< T >.Push(), Loyc.Collections.WListBase< T >.Push(), Loyc.MiniTest.Assert.That(), Loyc.Collections.VListBlock< T >.ToArray(), and Loyc.Collections.FVList< T >.ToFWList().
WList<T> Loyc.Collections.FWList< T >.ToWList () inline
Returns this list as an WList, which effectively reverses the order of the elements.
This operation marks the items of the list as immutable. You can modify either list afterward, but some or all of the list may have to be copied.
References Loyc.Collections.VListBlock< T >.EnsureImmutable().
FWList<T> Loyc.Collections.FWList< T >.Transform (VListTransformer< T > x) inline
Transforms a list (combines filtering with selection and more).
Parameters
x Method to apply to each item in the list
Returns
A list formed from transforming all items in the list
See the documentation of FVList.Transform() for more information.
References Loyc.Collections.VListBlock< T >.Transform().
FWList<T> Loyc.Collections.FWList< T >.WhereSelect (Func< T, Maybe< T >> filter) inline
Filters and maps a list with a user-defined function.
Parameters
filter A function that chooses which items to include in a new list, and what to change them to.
Returns
The list after filtering has been applied. The original list structure is not modified.
This is a smart function. If the filter does not modify the first N items it is passed (which are the last items in a FWList), those N items are typically not copied, but shared between the existing list and the new one.
Property Documentation
T Loyc.Collections.FWList< T >.First get
Returns the front item of the list (at index 0).
Referenced by Loyc.Collections.FWList< T >.ToArray().
T Loyc.Collections.FWList< T >.this[int index, T defaultValue] get
Gets an item from the list at the specified index; returns defaultValue if the index is not valid.