Enhanced C#: Loyc.StringBuilderExt Class Reference
Loyc.StringBuilderExt Class Reference
Extension methods that add some functionality of string to StringBuilder.
Source file:
/Core/Loyc.Essentials/Strings/StringBuilderExt.cs
Remarks
Extension methods that add some functionality of string to StringBuilder.
Static Public Member Functions
static string Substring (this StringBuilder sb, int startIndex, int length)
Extracts a substring from the specified StringBuiler.
static char Last (this StringBuilder str)
Returns the last character of the string
static char LastOrDefault (this StringBuilder str, char @default= '\0')
Returns the last character of the string, or a default character if the string is empty.
static StringBuilder TrimStart (this StringBuilder sb)
Removes all leading occurrences of spaces and tabs from the StringBuilder object.
static StringBuilder TrimStart (this StringBuilder sb, params char[] trimChars)
Removes all leading occurrences of the specified set of characters from the StringBuilder object.
static StringBuilder TrimEnd (this StringBuilder sb)
Removes all trailing occurrences of spaces and tabs from the StringBuilder object.
static StringBuilder TrimEnd (this StringBuilder sb, params char[] trimChars)
Removes all trailing occurrences of the specified set of characters from the StringBuilder object.
static StringBuilder Trim (this StringBuilder sb)
Removes all leading and trailing occurrences of spaces and tabs from the StringBuilder object.
static StringBuilder Trim (this StringBuilder sb, params char[] trimChars)
Removes all leading and trailing occurrences of the specified set of characters from the StringBuilder object.
static int IndexOf (this StringBuilder sb, char value, int startIndex=0)
Gets the index of a character in a StringBuilder
static int IndexOf (this StringBuilder sb, UString searchStr, int startIndex=0, bool ignoreCase=false)
Gets the index of a substring in a StringBuilder
static int LastIndexOf (this StringBuilder sb, char searchChar, int startIndex=int.MaxValue)
Gets the index of a character in a StringBuilder
static int LastIndexOf (this StringBuilder sb, UString searchStr, int startIndex=int.MaxValue, bool ignoreCase=false)
Gets the index of a substring in a StringBuilder
static bool EndsWith (this StringBuilder sb, UString what, bool ignoreCase=false)
Finds out whether the StringBuilder ends with the specified substring.
static bool StartsWith (this StringBuilder sb, UString what, bool ignoreCase=false)
Finds out whether the StringBuilder starts with the specified substring.
static bool SubstringEquals (StringBuilder sb, int start, UString what, bool ignoreCase=false)
Checks if the sequences of characters what is equal to sb.Substring(start, what.Length), without actually creating a substring object.
static char TryGet (this StringBuilder s, int index)
static char TryGet (this StringBuilder s, int index, char defaultValue)
static StringBuilder AppendCodePoint (this StringBuilder s, int c)
Appends a unicode code point in the range 0 to 0x10FFFF to StringBuilder in UTF-16.
Member Function Documentation
static StringBuilder Loyc.StringBuilderExt.AppendCodePoint (this StringBuilder s, int c) inline static
Appends a unicode code point in the range 0 to 0x10FFFF to StringBuilder in UTF-16.
Exceptions
ArgumentOutOfRangeException Invalid character c
NullReferenceException null StringBuildre
static bool Loyc.StringBuilderExt.EndsWith (this StringBuilder sb, UString what, bool ignoreCase = false) inline static
Finds out whether the StringBuilder ends with the specified substring.
static int Loyc.StringBuilderExt.IndexOf (this StringBuilder sb, char value, int startIndex = 0) inline static
Gets the index of a character in a StringBuilder
Returns
Index of the first instance of the specified character in the string, or -1 if not found
static int Loyc.StringBuilderExt.IndexOf (this StringBuilder sb, UString searchStr, int startIndex = 0, bool ignoreCase = false) inline static
Gets the index of a substring in a StringBuilder
Returns
Index of the first instance of the specified substring in the StringBuilder, or -1 if not found
static char Loyc.StringBuilderExt.Last (this StringBuilder str) inline static
Returns the last character of the string
static int Loyc.StringBuilderExt.LastIndexOf (this StringBuilder sb, char searchChar, int startIndex = int.MaxValue) inline static
Gets the index of a character in a StringBuilder
Returns
Index of the last instance of the specified character in the StringBuilder, or -1 if not found
static int Loyc.StringBuilderExt.LastIndexOf (this StringBuilder sb, UString searchStr, int startIndex = int.MaxValue, bool ignoreCase = false) inline static
Gets the index of a substring in a StringBuilder
Returns
Index of the last instance of the specified substring in the StringBuilder, or -1 if not found
static char Loyc.StringBuilderExt.LastOrDefault (this StringBuilder str, char @ default = '\0') inline static
Returns the last character of the string, or a default character if the string is empty.
static bool Loyc.StringBuilderExt.StartsWith (this StringBuilder sb, UString what, bool ignoreCase = false) inline static
Finds out whether the StringBuilder starts with the specified substring.
static string Loyc.StringBuilderExt.Substring (this StringBuilder sb, int startIndex, int length) inline static
Extracts a substring from the specified StringBuiler.
static bool Loyc.StringBuilderExt.SubstringEquals (StringBuilder sb, int start, UString what, bool ignoreCase = false) inline static
Checks if the sequences of characters what is equal to sb.Substring(start, what.Length), without actually creating a substring object.
static StringBuilder Loyc.StringBuilderExt.Trim (this StringBuilder sb) inline static
Removes all leading and trailing occurrences of spaces and tabs from the StringBuilder object.
References Loyc.StringBuilderExt.Trim().
Referenced by Loyc.StringBuilderExt.Trim().
static StringBuilder Loyc.StringBuilderExt.Trim (this StringBuilder sb, params char[] trimChars) inline static
Removes all leading and trailing occurrences of the specified set of characters from the StringBuilder object.
Parameters
trimChars An array of Unicode characters to remove.
References Loyc.StringBuilderExt.TrimEnd(), and Loyc.StringBuilderExt.TrimStart().
static StringBuilder Loyc.StringBuilderExt.TrimEnd (this StringBuilder sb) inline static
Removes all trailing occurrences of spaces and tabs from the StringBuilder object.
References Loyc.StringBuilderExt.TrimEnd().
Referenced by Loyc.StringBuilderExt.Trim(), and Loyc.StringBuilderExt.TrimEnd().
static StringBuilder Loyc.StringBuilderExt.TrimEnd (this StringBuilder sb, params char[] trimChars) inline static
Removes all trailing occurrences of the specified set of characters from the StringBuilder object.
Parameters
trimChars An array of Unicode characters to remove.
static StringBuilder Loyc.StringBuilderExt.TrimStart (this StringBuilder sb) inline static
Removes all leading occurrences of spaces and tabs from the StringBuilder object.
References Loyc.StringBuilderExt.TrimStart().
Referenced by Loyc.StringBuilderExt.Trim(), and Loyc.StringBuilderExt.TrimStart().
static StringBuilder Loyc.StringBuilderExt.TrimStart (this StringBuilder sb, params char[] trimChars) inline static
Removes all leading occurrences of the specified set of characters from the StringBuilder object.
Parameters
trimChars An array of Unicode characters to remove.