Enhanced C#: Loyc.LLParserGenerator.Program Class Reference
Loyc.LLParserGenerator.Program Class Reference
Entry point of LLLPG.exe, with QuickRun() method to help invoke LLLPG programmatically.
Source file:
/Main/LLLPG/Program.cs
Remarks
Entry point of LLLPG.exe, with QuickRun() method to help invoke LLLPG programmatically.
Static Public Member Functions
static void Main (params string[] args)
static string QuickRun (string input, params Assembly[] macroAssemblies)
Run macro processor for LLLPG on the specified input, with the specified command-line option map, returning the result as a string.
static string QuickRun (IParsingService inputLang, int maxExpand, string input, params Assembly[] macroAssemblies)
static int Test_LLLPG ()
Member Function Documentation
static string Loyc.LLParserGenerator.Program.QuickRun (string input, params Assembly[] macroAssemblies) inline static
Run macro processor for LLLPG on the specified input, with the specified command-line option map, returning the result as a string.
References Loyc.Syntax.ParsingService.Current, Loyc.Syntax.ParsingService.PushCurrent(), Loyc.Syntax.LNode.PushPrinter(), Loyc.MiniTest.RunTests.RunMany(), and Loyc.MessageSink.Trace.