Enhanced C#: Loyc.Syntax.LNodePrinter Class Reference
Loyc.Syntax.LNodePrinter Class Reference
Standard extension methods for ILNodePrinter.
Source file:
/Core/Loyc.Syntax/LNodes/ILNodePrinter.cs
Remarks
Standard extension methods for ILNodePrinter.
Static Public Member Functions
static string Print (this ILNodePrinter printer, LNode node, IMessageSink sink=null, ParsingMode mode=null, ILNodePrinterOptions options=null)
Serializes the specified syntax tree to a string in the syntax supported by the specified ILNodePrinter.
static string Print (this ILNodePrinter printer, IEnumerable< LNode > nodes, IMessageSink sink=null, ParsingMode mode=null, ILNodePrinterOptions options=null)
Serializes a list of syntax trees to a string in the syntax supported by the specified ILNodePrinter.
static StringBuilder PrintMultiple (ILNodePrinter printer, IEnumerable< LNode > nodes, StringBuilder sb, IMessageSink sink, ParsingMode mode, ILNodePrinterOptions options)
Converts a sequences of LNodes to strings, adding a line separator between each.
Member Function Documentation
Print() [1/2]
static string Loyc.Syntax.LNodePrinter.Print (this ILNodePrinter printer, IEnumerable< LNode > nodes, IMessageSink sink = null, ParsingMode mode = null, ILNodePrinterOptions options = null) inline static
Serializes a list of syntax trees to a string in the syntax supported by the specified ILNodePrinter.
References Loyc.Syntax.ILNodePrinter.Print().
Print() [2/2]
static string Loyc.Syntax.LNodePrinter.Print (this ILNodePrinter printer, LNode node, IMessageSink sink = null, ParsingMode mode = null, ILNodePrinterOptions options = null) inline static
Serializes the specified syntax tree to a string in the syntax supported by the specified ILNodePrinter.
References Loyc.Syntax.ILNodePrinter.Print().
PrintMultiple()
static StringBuilder Loyc.Syntax.LNodePrinter.PrintMultiple (ILNodePrinter printer, IEnumerable< LNode > nodes, StringBuilder sb, IMessageSink sink, ParsingMode mode, ILNodePrinterOptions options) inline static
Converts a sequences of LNodes to strings, adding a line separator between each.
Parameters
printer Printer to be used for each single LNode.
The newline between two nodes is suppressed if the second node has a appendStatement attribute.
References Loyc.Syntax.ILNodePrinterOptions.NewlineString.
Referenced by Loyc.Syntax.Les.Les2LanguageService.Print(), and Loyc.Ecs.EcsLanguageService.Print().