Enhanced C#: Loyc.Syntax.IParsingService Interface Reference
Loyc.Syntax.IParsingService Interface Reference
An interface that encapsulates the lexer, parser, and printer of a programming language, or a non-programming language that can be represented by Loyc trees.
Source file:
/Core/Loyc.Syntax/IParsingService.cs
Remarks
An interface that encapsulates the lexer, parser, and printer of a programming language, or a non-programming language that can be represented by Loyc trees.
The simplest way to parse code is with the extension method Parse(string, IMessageSink msgs = null, Symbol inputType = null). The simplest way to print is with Print(LNode, IMessageSink)
The ToString() method should return a string that indicates the programming language represented by this object, e.g. "Enhanced C#".
See also
ParsingService
Properties
IEnumerable< string > FileExtensions [get]
Standard file extensions for this language, without leading dots, with the first one being the most common.
bool HasTokenizer [get]
Returns true if the Tokenize method is available.
bool CanPreserveComments [get]
Returns true if the parser supports preserving comments.
LNodePrinter Printer [get]
Gets a printer delegate that you can use with LNode.Printer and LNode.PushPrinter, or null if there is no corresponding printer available for the parser reresented by this object.
Public Member Functions
ILexer< Token > Tokenize (ICharSource text, string fileName, IMessageSink msgs)
Returns a lexer that is configured to begin reading the specified file.
IListSource< LNode > Parse (ICharSource text, string fileName, IMessageSink msgs, ParsingMode inputType=null, bool preserveComments=false)
Parses a source file into one or more Loyc trees.
IListSource< LNode > Parse (ILexer< Token > input, IMessageSink msgs, ParsingMode inputType=null, bool preserveComments=false)
If HasTokenizer is true, this method accepts a lexer returned by Tokenize() and begins parsing.
IListSource< LNode > Parse (IListSource< Token > tokens, ISourceFile file, IMessageSink msgs, ParsingMode inputType)
Parses a token tree, such as one that came from a token literal.
string Print (LNode node, IMessageSink msgs=null, object mode=null, string indentString="\t", string lineSeparator="\n")
Converts the specified syntax tree to a string.
Member Function Documentation
IListSource<LNode> Loyc.Syntax.IParsingService.Parse (ICharSource text, string fileName, IMessageSink msgs, ParsingMode inputType = null, bool preserveComments = false)
Parses a source file into one or more Loyc trees.
Parameters
text input file or string.
fileName A file name to associate with errors, warnings, and output nodes.
msgs Error and warning messages are sent to this object.
inputType Indicates the kind of input, e.g. File (an entire source file), FormalArguments (function parameter list), etc. null is a synonym for File.
preserveComments Whether to preserve comments and newlines by attaching trivia attributes to the output. If the property CanPreserveComments is false, this parameter will not work.
Implemented in Loyc.Ecs.EcsLanguageService, Loyc.Syntax.Les.Les2LanguageService, and Loyc.Syntax.Les.Les3LanguageService.
Referenced by Loyc.Syntax.ParsingService.Parse(), and Loyc.Syntax.ParsingService.ParseSingle().
IListSource<LNode> Loyc.Syntax.IParsingService.Parse (ILexer< Token > input, IMessageSink msgs, ParsingMode inputType = null, bool preserveComments = false)
If HasTokenizer is true, this method accepts a lexer returned by Tokenize() and begins parsing.
Parameters
input A source of tokens.
msgs Error and warning messages are sent to this object.
inputType Indicates how the input should be parsed.
preserveComments Whether to preserve comments and newlines by attaching trivia attributes to the output. If the property CanPreserveComments is false, this parameter will not work.
Exceptions
NotSupportedException HasTokenizer is false.
This method adds any preprocessing steps to the lexer (tree-ification or token preprocessing) that are required by this language before it sends the results to the parser. If possible, the output is computed lazily.
Implemented in Loyc.Ecs.EcsLanguageService, Loyc.Syntax.Les.Les2LanguageService, and Loyc.Syntax.Les.Les3LanguageService.
IListSource<LNode> Loyc.Syntax.IParsingService.Parse (IListSource< Token > tokens, ISourceFile file, IMessageSink msgs, ParsingMode inputType)
Parses a token tree, such as one that came from a token literal.
Parameters
tokens List of tokens
file A source file to associate with errors, warnings, and output nodes.
msgs Error and warning messages are sent to this object.
inputType Indicates how the input should be parsed.
Some languages may offer token literals, which are stored as token trees that can be processed by "macros" or compiler plugins. A macro may wish to parse some of the token literal using the host language's parser (e.g. LLLPG needs to do this), so this method is provided for that purpose.
Exceptions
NotSupportedException This feature is not supported by this parsing service.
Implemented in Loyc.Ecs.EcsLanguageService, Loyc.Syntax.Les.Les2LanguageService, and Loyc.Syntax.Les.Les3LanguageService.
string Loyc.Syntax.IParsingService.Print (LNode node, IMessageSink msgs = null, object mode = null, string indentString = "\t", string lineSeparator = "\n")
Converts the specified syntax tree to a string.
Parameters
node A syntax tree to print.
msgs If errors or warnings occur during printing, they are sent here. If this is null, messages shall be sent to MessageSink.Current.
mode Language-defined configuration. It is suggested that the printing service should accept the members of ParsingMode (e.g. ParsingMode.Statements) as possible printing modes.
indentString Indent character for multi-line nodes
lineSeparator Newline string for multi-line nodes
Implemented in Loyc.Ecs.EcsLanguageService, Loyc.Syntax.Les.Les2LanguageService, and Loyc.Syntax.Les.Les3LanguageService.
ILexer<Token> Loyc.Syntax.IParsingService.Tokenize (ICharSource text, string fileName, IMessageSink msgs)
Returns a lexer that is configured to begin reading the specified file.
Parameters
text Text to be tokenized (e.g. UString)
fileName File name to be associated with any errors that occur.
msgs Error messages are sent to this object.
The returned lexer should be a "simple" tokenizer. If the language uses tree lexing (in which tokens are grouped by parentheses and braces), the returned lexer should NOT include the grouping process.
It is recommended that the implementation of this method filter out spaces (for best performance) but not comments or newlines. If there is a preprocessor, it should not run.
Implemented in Loyc.Ecs.EcsLanguageService, Loyc.Syntax.Les.Les2LanguageService, and Loyc.Syntax.Les.Les3LanguageService.
Referenced by Loyc.Syntax.ParsingService.Tokenize().
Property Documentation
bool Loyc.Syntax.IParsingService.CanPreserveComments get
Returns true if the parser supports preserving comments.
IEnumerable<string> Loyc.Syntax.IParsingService.FileExtensions get
Standard file extensions for this language, without leading dots, with the first one being the most common.
Referenced by Loyc.Syntax.ParsingService.Register(), and Loyc.Syntax.ParsingService.Unregister().
bool Loyc.Syntax.IParsingService.HasTokenizer get
Returns true if the Tokenize method is available.
LNodePrinter Loyc.Syntax.IParsingService.Printer get
Gets a printer delegate that you can use with LNode.Printer and LNode.PushPrinter, or null if there is no corresponding printer available for the parser reresented by this object.
Referenced by LeMP.Compiler.CompleteInputOutputOptions(), and Loyc.Syntax.ParsingService.PrintMultiple().